### ISSUE TITLE
PS3 content mislabeled as PSP content (and possibly more)

### ISSUE THREAD

**Issue by Rezon1987** [RePod/psdle#11]
I've noticed that very small batch of my PS3 games and avatars is mislabled as PSP content on PSDLE. I've tried with and without enabling "Catalog" before generating the list. I guess it's because, for some weird reason, you can get the .xpd file from Account Management on the SEN website (to be used with PSN downloader) and on Media Go, you could download the .PKG files for these items, something that is usually reserved only to PSP content. I can give you a few examples:

Flower/Flowery (avatars)
Vacation and Wild Costumes Compatibility Packs for Ultra Street Fighter IV
THEXDER Neo (the PS3 version! the game is also on PSP but i have only the PS3 version, and it's labeled as PSP)
SD movie trailers (i only have two of them, but have the same problem)

I'm also wondering how you're going to handle content that works on multiple systems. For example, i have Warhawk and Twisted Metal, they're labeled as "PS1", however i also have Theme Hospital and the two Oddworld games, and they're labeled as "PSP". The PSP Minis i own are labeled as PSP for obvious reasons (the "main platform"?), but they also work on PS3 and Vita.

Also, RESOGUN for PS3 is mislabeled as a Vita title. The game is cross-buy, so i basically see 1 entry for the PS4 game and TWO Vita entries.

On a final note, in this page: https://github.com/RePod/psdle/issues/7

You're asked if it will be possible to export icons. You replied, but i really didn't understand this part:

"However, running JSON.stringify(repod.psdle.gamelist_cur) in the console will return a string of all information PSDLE has on the current view in JSON format. Paired with prompt() you should be able to easily copy it."

The issue was closed and no other replies have been made. Care to elaborate how to use that?

ps: i also have other questions, especially regarding the extra filters that show up if you enable "Catalog" (i.e. Unknown), but i'll keep them for later.

**Comment by RePod** [comment]
Using "Generate Fake List" on a search results page, I'm getting the following results: (sizes, PS+, and date are random)

![screenshot_2](https://cloud.githubusercontent.com/assets/7897871/6089832/04ef7cf0-ae37-11e4-96e7-c9e35f2da132.png)
![screenshot_18](https://cloud.githubusercontent.com/assets/7897871/6089793/7653d842-ae36-11e4-8780-ccf5a10ebd4f.png)

Seems to be working as intended, at least on the en-us store. As for the videos, I thought my content checks were good enough but I'll have to back and improve them.

**Comment by Rezon1987** [comment]
Well i'm not using the en-us store, it's not even the en-gb one (always the good old non-English stores like the other issues recently reported! quite funny isn't it)

About the command, it says repod is not defined...

**Comment by RePod** [comment]
What store language?

Also "repod" will not be available if using the Userscripts, as it is ran in a sandbox.

**Comment by Rezon1987** [comment]
it-it

**Comment by RePod** [comment]
I've been working on a few things, the Catalog being one of them.

If you're using the userscript please update to 2.021, or use the bookmarklet/direct method and tell me if you see changes.

>So i guess that command won't work for anyone except you right?

The command is available to anybody using PSDLE. However, userscripts are run in a sandbox (by the browser add-on/extension) which prevents accessing their contents (including functions and stored variables) externally.

**Comment by Rezon1987** [comment]
Yes, i notice differences when i choose "Catalog". There are also more options. Anyway, the aforementioned PS3 content is no longer listed as PSP.

So you said that the "Unknown" filter is for everything that doesn't get a Catalog response. I guess it's normal that it includes miscellaneous content, like DLC and apps? It even includes actual games like After Burner Climax and Resident Evil HD Remaster. The latter is quite recent.

ps: did you also add a "total size" at the bottom of the list? That's quite nice.

**Comment by RePod** [comment]
>There are also more options.

Everything to the right of "Unknown" are unexpected categories that don't weren't detected as everything to the left of "Unknown". You said you had SD Movie Trailers.

If these come up when you deselect everything from "Unknown" and to the left, please name them.

>So you said that the "Unknown" filter is for everything that doesn't get a Catalog response. ...

There's a fair amount of older content (usually deleted/delisted/defunct) that simply don't have a Catalog response and get logged under "Unknown" (recent example: YouTube Vita). I cannot do anything about this. A search on the it-it store and a trip to Google revealed that After Burner Climax was delisted.

>ps: did you also add a "total size" at the bottom of the list? That's quite nice.

Yep.

**Comment by Rezon1987** [comment]
I guess these new categories will disappear again in the future?

Oh, and nevermind, i've just checked and i see 2 entries for the SD trailers i have: one is PS3 and the other is PSP. I apologize for the inconvenience.

I don't think Unknown properly list all older content, as it's listing a truckload of content that wasn't definitely delisted, deleted or changed. I guess i'll have to live with it anyway, it's their fault.

Oh, and i think that certain PSOne Classics are labeled as "PS1" because they're not obtained from the store, but by redeeming vouchers, i.e. the ones you could obtain from a old Playstation Home event back in 2013/3014. The same applies on both en-us and it-it stores, and i guess all the others. The others i've obtained from the store itself are labeled as "PSP", even if i didn't buy them directly (i.e. both Oddworld games from "The Oddboxx").

And can you please check if, in the en-us store, RESOGUN for PS3 is properly labeled as "PS3"? Because it isn't in mine, it's "PS Vita".

**Comment by RePod** [comment]
>I guess these new categories will disappear again in the future?

They're there for safety. I'll probably leave them there for testing things out and making sure everything on the list can be dealt with (with categories, anyway).

Currently it seems the biggest cause of mislabeled systems were the Catalog responses having weird data. The early Final Fantasy PSP games, despite being native to the PSP, had information claiming they were "PS1 Classics". This has been fixed.

>And can you please check if, in the en-us store, RESOGUN for PS3 is properly labeled as "PS3"?

I can confirm from my own list that each is listed properly. I will look into this on it-it.

**Comment by RePod** [comment]
Looked into it on it-it. Resogun (at least in search) is shown as a single item for PS4/3/Vita while en-us lists each separately.

Unfortunately PSDLE cannot recreate the Entitlements to test this further by me.

Could you please run this in your browser console (Firefox: Ctrl+Shift+K, Chrome:Ctrl+Shift+J) and paste the results?

It will loop through the same information PSDLE uses, searching for "RESOGUN" and spitting out the would-be detected information.

````
$.each(gEntitlementManager.getAllEntitlements(),function(i,obj) {
	var c = !1; if (obj.drm_def || obj.entitlement_attributes) { c = !0; }
	if (c) {
		var name = (obj.drm_def) ? obj.drm_def.contentName : obj.game_meta.name;
		if (name.indexOf("RESOGUN") > -1) {
			var platform, pids = 0;
			if (obj.game_meta) { platform = ["PS4"] }
			else { 
				platform = []; pids = obj.drm_def.drmContents[0].platformIds;
				$.each({"1":KamajiPlatformFlags.PS3,"3": KamajiPlatformFlags.PSP,"8":KamajiPlatformFlags.VITA}, function (t,u) { 0 !== (pids >>> 1 & u >>> 1) && platform.push(KamajiPlatforms[Number(t)]); });
			}
			//Remove personal information (such as dates) and extraneous URLs.
			var safe = JSON.stringify(obj, function(k,v) { if(/[\d\-]+T.+Z$/.test(v) || /^http/.test(v)) { return "~" } return v; });
			console.log(i,platform,pids,safe)
		}
	}
})
````

**Comment by Rezon1987** [comment]
Is that good for you? http://pastebin.com/7LekFEEe

And yes, RESOGUN is a single item in Europe, i don't know why. Fun fact: getting that "bundle" overwrote my PS+ entitlement for the PS4 edition, basically making all versions permanently mine. The same happened to other games like Thomas Was Alone but i think they're all labeled properly unlike this one.

**Comment by RePod** [comment]
Yes, this is fine.

Based on this information the PS3 and Vita version share the same platform ID data. What systems do they show on the actual download list? If you need help finding them hover over the icon in PSDLE to get the estimate page number, or if I had to guess page 36 (PS4) or 87 (PS3/Vita).

**Comment by Rezon1987** [comment]
Didn't know you added a feature like that. Anyway, they both show the PS3 and Vita icons. I would need to download them... the problem is, the download list on PS3, the one on the SEN site, and the one on the Plastation Store, are NOT THE SAME. For example, on the Store website, RESOGUN for PS3/Vita is on page 20.

**Comment by RePod** [comment]
Between the information you provided and the it-it Catalog responses I don't think it's possible to differentiate between them.

While I could *guess* based on the size or product ID, if I start doing this for every game it'll turn into a game of cat and mouse.
