### ISSUE TITLE
Disabling "Catalog" gives 0 results, and item counter bug

### ISSUE THREAD

**Issue by EvilCanasta** [RePod/psdle#12]
I think this problem appeared with one of the latest revisions of this plugin.

Before that, by disabling "Catalog", the resulting list took a lot less time to be created, but it's probably less accurate (as implied by the description), now you don't even get basic filters anymore.

Also, i've noticed something strange: when you start creating the list (with all options enabled) the item counter starts at 240-something, then it DECREASES, and increases again like nothing ever happened. You still get the full list after that, though.

ps: will there ever be a way to completely disable the list window after you stop using it? I know you can simply reload the page, but the SEN one is not exactly one of the fastest sites in the world. I've tried disabling all filters but it still covers the search bar and the account options.

Oh and another thing: did you remove the PS2 filter for PS2 Classics? I don't have many PS2 titles, but they're listed as PS3 now. I guess it's because they're only for PS3?

**Comment by RePod** [comment]
>Disabling "Catalog" gives 0 results

I am unable to replicate this behavior and probably will not be able to since this seems to be a problem with the Entitlements. What happens if you try after logging out and back in or visiting the Download List first?

>now you don't even get basic filters anymore.

Disabling the Catalog disables filters (Game, Demo, etc.) which are determined from the Catalog. No Catalog, no filters.

>then it DECREASES, and increases again like nothing ever happened. 

This is an issue due to a recent Catalog change I made. Nothing's broken, PSDLE just can't count.

>ps: will there ever be a way to completely disable the list window after you stop using it?

It's available internally as *repod.psdle.debug.die()* but not on the interface. Eventually I'll get around to doing this.

>did you remove the PS2 filter for PS2 Classics?

No, and the ones I have are still working fine. Please link them or name them and their store region so I can look into it.

**Comment by EvilCanasta** [comment]
Thanks for the reply.

- I tried logging out and back, still the same. If i don't visit the Download List, it says "0 / 0" results, if i visit it, it says "0 / ####" (my current total of items)

- Yeah, i know that disabling Catalog disables them, but before the bug happened, you could still get the filters for the systems (PS1/PS2/PS3/etc.), now i'm only getting the buttons for Export View and CSV download.

- Twisted Metal Black and Stuntman Ignition, both in the Italian store. The former comes in multiple copies, because of the manuals.

**Comment by RePod** [comment]
I pushed an update (userscript 2.033 and direct equivalent), please try either of those and see if the problem persists before I continue.

Also for clarification:
* Is this on the mobile site?
* What browser?

If you're not using the userscript, after the list would be generated please run the following command in your browser console (Firefox: Ctrl+Shift+K, Chrome: Ctrl+Shift+J) and paste the result:
`console.log(repod.psdle.gamelist.length,repod.psdle.gamelist_cur.length)`

**Comment by EvilCanasta** [comment]
I visit the site from PC using the latest version of Firefox. I didn't notice anything different with the new update except for Stuntman Ignition which is recognized as a PS2 title once again.

I don't understand what to do with that command. I choose "Direct" from the PSDLE site but nothing happens.

**Comment by RePod** [comment]
Please do the following:
* Disable the Userscript if you have it enabled
* Open the console (`Ctrl+Shift+K`)
* Paste the contents of [this link](https://gist.githubusercontent.com/RePod/47e620e9de32104cf050/raw/44823bd74346751f08ba032a07bce876cb106e25/gistfile1.js)
* Press Enter to submit

The link contains a minor change to the code which disables a recent Catalog change. If this fixes the issue, I will have located the source and will begin working on it.

**Comment by EvilCanasta** [comment]
That's all i'm getting:

"PSDLE | Ready."
"PSDLE | Init."
POST https://store.sonyentertainmentnetwork.com/event/batch [HTTP/1.1 200 OK 10563ms]
POST https://store.sonyentertainmentnetwork.com/event/batch [HTTP/1.1 200 OK 1193ms]
POST https://store.sonyentertainmentnetwork.com/event/batch 
"An error occured sending an event to Kamaji Events API! error: timeout : timeout"

**Comment by RePod** [comment]
Did you attempt using PSDLE (with that link's contents) as normal? Use only that link to start PSDLE. No userscript, bookmarklet, or any other method.

Seems to be working for me on the *it-it* webstore.

**Comment by EvilCanasta** [comment]
Sorry, i don't get it... what do you mean with "normal"? I normally use it through Greasemonkey, which was already disabled. I used the "Direct" version from your site, and pasted the stuff from a couple of posts ago in the console, and it gives nothing, i pasted the content of that other link, and it gives nothing. I normally don't do things like that, sorry for any inconvenience.

**Comment by RePod** [comment]
By just using the link provided above you should be able to access PSDLE after posting the contents into the console and submitting it. If you are unable to, that's another issue that needs to be addressed.

**Comment by EvilCanasta** [comment]
Oh, ok, sorry, now i understand what to do, will try again.

ps: the counter seems to be working properly with that method. It starts from zero.

**Comment by RePod** [comment]
Please try [this link](https://raw.githubusercontent.com/RePod/psdle/84d144a1d9f02a1b06eac2cb6b98d5b3af148cb8/psdle.js) (of an older version).

This older version has hard coded systems to display, which may or may not be the issue.

**Comment by EvilCanasta** [comment]
I don't understand what you mean with "when the list would be displayed"? I ran that and it displayed a single line of code. Anyway, the plugin has become super sloooow lately...

ps do you know anything regarding the other stuff mentioned in my previous post?

**Comment by RePod** [comment]
>"when the list would be displayed"

When it shows "0 / ####", submit `repod.psdle.sys_cache` into the console.

As for mislabeled systems while I know a bit about the Catalog, I don't know everything. A lot of the information from it I use to figure these things out overlaps and may cause false positive. For instance, some of the Final Fantasy PSP ports/remakes, despite being PSP games are also considered "PS1 Classics".

**Comment by EvilCanasta** [comment]
Well i'm getting this:

Object { vita: "PS Vita", ps4: "PS4", ps3: "PS3", psp: "PSP", ps1: "PS1", ps2: "PS2" }

The "older version" gives me "#### / ####" items like before, when i don't select Catalog (and filters for PS3/PS4/PSP/Vita, the PS1/PS2 games listed under their respective categories go under PS3 because i didn't select Catalog)

Do you know why using the plugin has become more resource demanding and a lot slower than before? Is that because of changes on PSN or the latest versions of the plugin?

**Comment by RePod** [comment]
>Do you know why using the plugin has become more resource demanding and a lot slower than before? Is that because of changes on PSN or the latest versions of the plugin?

As far as PSDLE is concerned, it's not doing much more than it has before (except for storing more information from the Catalog, which you're not using). I have no information about the performance of the webstore itself.

This time I have two steps that need to be done:
* Try [this version](https://gist.githubusercontent.com/RePod/47e620e9de32104cf050
/raw/97cbc51c45310c1f6f0b19cee38caad3cfa34e9d/gistfile1.js) which tries to fix what I assume is a timing issue (the system cache isn't being generated before the table needs it).
* If that doesn't fix it, try clicking "Queue" on the menu then "List" to go back to the list and see if that resolves it. If it does, then it is indeed a timing issue.

**Comment by EvilCanasta** [comment]
It gives me 404 error.

**Comment by RePod** [comment]
Whoops, updated.

**Comment by EvilCanasta** [comment]
The list is created after i use that version, what now?

**Comment by RePod** [comment]
I went ahead and made an Italian PSN account to speed up the process and make your life easier before throwing a million more files and commands at you and found the cause!

Before I push it to live, please verify [this version](https://raw.githubusercontent.com/RePod/psdle/fdd88446f3a55fc62625fbffcd5188334f21dda7/psdle.js) which I just pushed before making this post.

**Comment by EvilCanasta** [comment]
Well that one creates a list without Catalog enabled, but the "decreasing counter" bug has returned :D

**Comment by RePod** [comment]
That's another issue entirely, it's been commented out this entire time.

I'll take this as meaning it's fixed. If you have any other issues (aside from PSDLE not knowing how to count), feel free to make a new issue.

**Comment by EvilCanasta** [comment]
It's not really fixed, but i've opened a new issue.
