### ISSUE TITLE
PlayStation Plus titles only export

### ISSUE THREAD

**Issue by florisvaneck** [RePod/psdle#13]
When I filter only my games and then use the toggle to show only PS+ titles (subscription) the export view option still exports all the titles (including the non-PS+ titles that I bought). 

I would like to see an extra column (instead of border around box cover) that indicates PS+/Non-PS+ so it is easier to filter those titles out. 

Otherwise great script! Keep up the good work.

**Comment by RePod** [comment]
You mean an extra column in the "Export View" or "CSV" output? Definitely a WIP.

I could just throw it in but I'm also considering what other information people are looking from the export.

**Comment by RePod** [comment]
This should be resolved, please go try it out and let me know if it's working as intended.

Also due to how I completely rewrote the exporting options (and things it leverages), the totals (previously just size) are not included in the export for now.

**Comment by EvilCanasta** [comment]
I think it can considered solved now? I've tried and it exports just a few hundreds of rows (and they're all the PS+ titles)

**Comment by florisvaneck** [comment]
Everything is working now. Really helps. Thanks, great!

—
Floris van Eck
