### ISSUE TITLE
Demos with a time limit, treated like PS+ content

### ISSUE THREAD

**Issue by Arka9** [RePod/psdle#17]
Hi, i'm reporting a minor issue with your userscript. I recently went on a Demo/Trial download frenzy (don't ask me why hahaha) and discovered that there are at least two demos that come with a 3-day time limit: Numblast Demo for both PSP and PS3. When i generate the list using PSDLE, they have the PS+ yellow border on the icons. Under Account Management on my PSN account, they have an expiration date, but it's NOT the same as my PS+ subscription: it's just 3 full days. I tried searching and apparently it just disappears from the download list after it has expired. Do you think it's possible to differentiate between actual PS+ content and minor stuff like this?

Also another minor issue: sometimes, PSDLE gives a list with 0/0 items, instead of actually creating it. It doesn't even starts the counter. I guess it has to do with recent changes on the Playstation Store itself, right? But it works most of the times anyway.

And the download queue, why doesn't the PSDLE queue uses the same item limit from the actual Store website? I think the limit there is something between 35~100 (probably the latter), but i managed to add more than 100 items, however the site couldn't display all of them at the same time.

Thank you in advance.

**Comment by RePod** [comment]
>Do you think it's possible to differentiate between actual PS+ content and minor stuff like this?
Most likely possible. Having not used PS+ trials I don't have content to test it with.

Could you please run this in your browser console (Firefox: Ctrl+Shift+K, Chrome:Ctrl+Shift+J) on the store, while logged in, and paste the results? PSDLE does not need to be running.

````
$.each(gEntitlementManager.getAllEntitlements(),function(i,obj) {
    var c = (obj.drm_def||obj.entitlement_attributes)?!0:!1;
    if (c) {
        var name = (obj.drm_def) ? obj.drm_def.contentName : obj.game_meta.name;
        if (name.indexOf("Numblast") > -1) { console.log(obj); }
    }
})
````

>Also another minor issue: sometimes, PSDLE gives a list with 0/0 items, instead of actually creating it. It doesn't even starts the counter. ... But it works most of the times anyway.

Something, something. Blame the store. PSDLE accesses the user's entitlement information from the store context, so if it's empty that is what PSDLE gets. It seems to be intermittent so it's not something I'm worried about.

>And the download queue, why doesn't the PSDLE queue uses the same item limit from the actual Store website?

Laziness. I don't have a lot of information about the queue to work off so artificially limiting it wouldn't be in my best interest. If they're all listed when viewed in PSDLE it's simply the store's representation not following through. However, if any real problems involving the queue do present themselves they should be displayed.

**Comment by Arka9** [comment]
Here are the results you asked for (?)

Array [ Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, altri 3390… ]
Object { active_date: "2015-04-26T12:07:09Z", active_flag: false, drm_def: Object, entitlement_type: 2, feature_type: 0, id: "EP9000-NPEA90040_00-0000000000000000", inactive_date: "2015-04-26T12:07:09Z", is_consumable: false, license: Object, pre_order_place_holder_flag: false, altri 7… }
Object { active_date: "2015-04-26T14:18:45Z", active_flag: false, drm_def: Object, entitlement_type: 2, feature_type: 0, id: "EP9000-NPEG90014_00-0000000000000000", inactive_date: "2015-04-26T14:18:45Z", is_consumable: false, license: Object, pre_order_place_holder_flag: false, altri 7… }

**Comment by RePod** [comment]
Er, sorry, try this one:

````
$.each(gEntitlementManager.getAllEntitlements(),function(i,obj) {
    var c = (obj.drm_def||obj.entitlement_attributes)?!0:!1;
    if (c) {
        var name = (obj.drm_def) ? obj.drm_def.contentName : obj.game_meta.name;
        if (name.indexOf("Numblast") > -1) { console.log(JSON.stringify(obj)); }
    }
})
````

Should be a bit more readable.

**Comment by Arka9** [comment]
http://pastebin.com/mSMQUwBL

**Comment by RePod** [comment]
I can say the PS+ checks *are* working properly. The content has all the right information, specifically expiry information, as you previously mentioned. The problem here is PSDLE does not validate that expiry information (in the case of things that *ARE* expired). As far as I know these types of demos/trials are through PS+, so it's not all wrong.

However, what I'm interested in is if this means *actual* expired PS+ content remains on the Entitlements list. To learn this I would need someone with a lapsed subscription to test it out and report their findings. I have a candidate in mind, let me reach out to them and see if they'll help out.

If the findings show that PS+ content does stick around instead of hiding expired entries I could use a red border instead of a yellow, indicating it is PS+ content (in some form) but has expired.

**Comment by Arka9** [comment]
No, the Numblast Demo is not PS+ content... it's not one of those games you could try for 1 hour or something, it's something else. It doesn't even have yellow text in the Store page.

**Comment by RePod** [comment]
Still waiting on a response from the person I contacted, which may be a while, but if that is the case I guess I can go with my original idea of making the border red instead of yellow.

**Comment by Arka10** [comment]
Hi, it's me again (with a different account though, as i've lost the other one), any news about this issue? If not, feel free to close it.

**Comment by RePod** [comment]
I got variable feedback from users with expired PS+ content with some stating PSDLE shows their expired games and other stating it doesn't.

I really don't know how to treat this aside from giving it an explicit option which is on my growing TO-DO list.

**Comment by Hyenard** [comment]
I had a similar issue, and the items just disappeared from the list. 

They didn't even reappear in the PSDLE list.

**Comment by RePod** [comment]
Hello @Arka10 hopefully you're still active (unfortunately, a month later).

I went ahead and decided to finally do something about this, and in the easiest way (for expanding it later) possible.

Please [run this version of PSDLE](https://gist.githubusercontent.com/RePod/a8b31f461561ac8dce4a/raw/81e415cedc7221f33cef4c137f88a122a9c7aed6/PSDLE) from your browser's console (Firefox: Ctrl+Shift+K, Chrome:Ctrl+Shift+J) .

I added an additional (crude) check that compares the dates of when content has gone inactive and the current date (if they have an "infinite_duration" value of false, indicating they SHOULD expire). If the conditions are met (expiration date has passed and it does not have *infinite_duration*), PSDLE will ignore it.

Thanks and sorry for the delay.

**Comment by Hyenard** [comment]
Well i'm not that guy but i have a question to ask: if the content just disappears from the official Download List, what is PSDLE supposed to "ignore"? o_O

**Comment by RePod** [comment]
PSDLE uses the same thing used to generate the Download List: entitlement data (which stores all services including games, videos, subscriptions tied to the account).

However, PSDLE does not accurately parse that entitlement data which leads to certain things that are ignored on the Download List popping up in PSDLE.

The biggest example, as demonstrated by this issue, is expired content. Before, PSDLE did not check if content was expired (aside from assuming it was PS+ content) before adding it to its internal list. Now it does care about expired content and ignores it (or just doesn't add it to the internal list) similar to the Download List's behavior.

**Comment by Hyenard** [comment]
Well, if i can help, tell me what i'm supposed to see from that version of PSDLE, because the weirdest thing i've seen was "e is not defined" and the two Numblast demos (yeah, i had to put them in my Download List) have that weird "404 Not Found" message in the console.

**Comment by RePod** [comment]
>the two Numblast demos

Apparently I didn't proof my code by debugging it after applying the fix, but I have now. @Hyenard please try [this version](https://raw.githubusercontent.com/RePod/psdle/66a8a9dd2214dd1e50677aa1c8a6be6e881ab280/psdle.js) (latest at time of writing) which has said fix.

Also, in the future, instead of adding problematic content to your list (regardless of if you want it) use the recently added `repod.psdle.debug.injectEntitlement()` command. @Arka9 / @Arka10 was kind enough to provide their entitlement data, and using this command lets PSDLE treat it like your own (pretty useful).

>what did you change in versions v2.049 and v2.050?

A lot, check the commit history. (including the following)

>Also why some PSP content is blue-ish now :O

Indicates PS Vita-compatible content.

**Comment by Hyenard** [comment]
So i need to wait until the content expires?

**Comment by RePod** [comment]
Yes.

**Comment by Hyenard** [comment]
Well, the demos have expired (they don't appear as "Purchased" in the Store), however this time, they're still in my download list. I'll post the results later.

**Comment by RePod** [comment]
If the Numblast demos are not displayed on Download List (at least) then them not showing up in PSDLE is accurate behavior.

----

>the missing item is the "Fix Me Hook Hat"

What is the ID and Product ID?

The ID is in the link available when hovering above the actual name:
![aa](https://cloud.githubusercontent.com/assets/7897871/8367840/c2737744-1b70-11e5-8129-2ef6ea1f847d.png)

The Product ID is on the icon:
![aa2](https://cloud.githubusercontent.com/assets/7897871/8367841/c288fc7c-1b70-11e5-9cf5-715b5d951cae.png)

**Comment by Hyenard** [comment]
EP9000-CUSA00762_00-LBPDLCORIGCO0131

**Comment by RePod** [comment]
Yes, if @Arka9 / @Arka10 has a similar issue they can re-open this.
