### ISSUE TITLE
New problem with the "export" function

### ISSUE THREAD

**Issue by Arka10** [RePod/psdle#19]
After creating the list, and choosing "Export View" and then "Enter delimiter", when i manually copy the resulting text in Excel, all the content from every row is in a single column, rather than being separated in different columns. That used to work properly before, probably with the previous version of the script. Now the only way to show them properly is to download the .CSV file and import it in Excel. 

Could you please look into it? Thanks.

![newissue](https://cloud.githubusercontent.com/assets/12598477/7799677/4e18c414-0309-11e5-9f60-c4a540bcb0b4.jpg)

ps: this happens with AND without "Catalog" enabled.

**Comment by RePod** [comment]
Please try out the latest version. If using the Userscript ensure it's version 2.046.

----

The problem was due to an old commit where I replaced all tab characters with four spaces which included this string. I future proofed it this time so hopefully it won't happen agian.
