### ISSUE TITLE
Catalog - LittleBigPlanet3, "Fix Me Hook Hat" (EP9000-CUSA00762_00-LBPDLCORIGCO0131)

### ISSUE THREAD

**Issue by RePod** [RePod/psdle#21]
@Hyenard please post the results of:

````javascript
repod.psdle.debug.entitlement("EP9000-CUSA00762_00-LBPDLCORIGCO0131","id")
````

----

The specific issue is that the PS4 version of the content is inheriting the system information from the Catalog which is shared by the PS3 version.

The PS4 version is getting a system value of `["PS3", "PS4"]` which *safeGuessSystem()* returns as literally "PS3 PS4" (which is therefore invalid).

**Comment by Hyenard** [comment]
3549 Array [ "PS4" ] 0 "{"active_date":"~","active_flag":true,"entitlement_attributes":[{"entitlement_key_flag":true,"package_file_size":0,"placeholder_flag":false,"platform_id":"ps4"}],"entitlement_type":5,"feature_type":0,"game_meta":{"icon_url":"~","name":"Maglietta Fix Me Hook Hat","package_type":"PS4AL","type":"PS4AL"},"id":"EP9000-CUSA00762_00-LBPDLCORIGCO0131","is_consumable":false,"preorder_flag":false,"preorder_placeholder_flag":false,"product_id":"EP9000-CUSA00762_00-LBPDLCORIGCO0131","revision_id":1346355428273,"sku_id":"EP9000-CUSA00762_00-LBPDLCORIGCO0131-E001","subs_flag":false,"use_count":0,"use_limit":0}"

**Comment by RePod** [comment]
Through the power of Entitlement Injection, I've found the problem: Catalog is returning supported systems as "PS3" and "PS4" (which is resulting in a system of "PS3 PS4").

I recall LBP DLC being cross-platform, so I assume this is the cause.

**Comment by Hyenard** [comment]
This is the first time it happens, they usually release multiple versions of the same DLC.

**Comment by RePod** [comment]
Yeah but if they somehow happen to share the Catalog info, and that Catalog info says that ID is compatible for both systems (which it might be), I can't really choose a system.

How does it appear on the Download List? Downloadable to PS3 and PS4, PS4?

**Comment by Hyenard** [comment]
It appears as not downloadable to anything in the actual list, lol. It has no download button. Smallest PS4 addons cannot be downloaded, they go under Services, they're like licences tied to your account. Going in its Store page, it tells it can be downloaded to PS3... and PS3. But that thing was never ever accurate. Only the actual PS3 version of the same addon, named "LBPDLCORIGCO0131" has a download button.

**Comment by Hyenard** [comment]
I wonder if this issue is similar to the other one with Resogun on Vita and PS3 being both labeled as Vita in the list. It was reported here many months ago.

**Comment by Hyenard** [comment]
Hi, it's me again. Feel free to close this issue, the problem fixed by itself several weeks ago. It hasn't happened to any other DLC since then.
