### ISSUE TITLE
Keeps stopping at 4831 items

### ISSUE THREAD

**Issue by JohnRoc** [RePod/psdle#23]
Hello! I love this nifty little tool for sorting the nightmare that is the PSN download list, but I've been having some problems with it recently. When I leave the default selections "Entitlements" and "Download Queue" it loads almost instantly and works well. However, when I try to add "Vita TV" to the selection, it just says "Please wait," indefinitely. It never does anything else. And lastly, when I try to select all options including "Catalog," it always gets hung around item 4,831 on the list. It just stops and stays there. It's frustrating because I like being able to sort everything by Add-On, Themes, etc. I don't know a whole lot about programming or computers, but if there's any more info you need, I'll do my best to provide it. I hope there's a fix for it. Thanks again for this awesome tool!
![ps store screenshot](https://cloud.githubusercontent.com/assets/14240460/9839902/8875d030-5a4c-11e5-9e84-4e77f5fa9fcb.png)

**Comment by RePod** [comment]
I'll assume the issue is also happening in Firefox, and since I know FF's environment a little better I'll use it while finding the problem.

To start, press *Ctrl+Shift+K* to open Firefox' console.
Then ensure the logging options (the top row with Net, CSS, etc.) are toggled like so:
![](https://i.imgur.com/QjWJseU.png)

My image was taken after the table was displayed, but do this before running PSDLE.

If any notable errors stand out, paste those here.

**Comment by JohnRoc** [comment]
Apologies for taking a while to get back to you, busy week. So I tried again following your example and it stopped at item 4982 this time. Only errors shown were four of the "TypeError: e is undefined" in a row. Just like in your example. Never gets to the "Table generated" completion part though. I pulled up the PS Store, opened the Firefox console, highlighted the same options you did, then ran PSDLE. No notable errors, though. :(

**Comment by RePod** [comment]
Run PSDLE and whatever number it stops on add 1 to it. Replace 123 in the following command with that number and execute it in the console.

````Javascript
prompt("",JSON.stringify(
    gEntitlementManager.getAllEntitlements()[123]
));
````

Paste the result of that here.

**Comment by JohnRoc** [comment]
>"{"active_date":"2015-04-20T04:49:36Z","active_flag":false,"drm_def":{"active_flag":false,"autoDownload":false,"availableDate":"2015-04-20T04:49:36Z","contentName":"Adventure Time: Explore The Dungeon Because I DON'T KNOW!","contentType":"GAME","downloadableStatus":"ready","drmContents":[{"bitrate":0,"contentId":"UP0367-NPUB31282_00-ADVENTURETMGMPKG","contentName":"Adventure Time: Explore The Dungeon Because I DON'T KNOW!","contentSize":901842000,"contentUrl":"http://zeus.dl.playstation.net/cdn/UP0367/NPUB31282_00/UYaMlzcSPXdQyUlIzwyrdkNBGajNqqbIAJuFkuDaCedySAqRYdlELRfPIbSEKtpj.pkg","downloadType":0,"drmContentType":1,"drmType":2,"gracePeriod":0,"platformIds":2147483648,"position":0,"spName":"D3 Publisher of America","titleName":"Adventure Time: Explore The Dungeon Because I DON'T KNOW!"}],"duration":0,"entitlementId":"UP0367-NPUB31282_00-ADVENTURETMGMPKG","firstPlayExpiration":0,"firstPlayExpirationHours":0,"image_url":"https://image.api.np.km.playstation.net/images/?format=png&image=http%3A%2F%2Fapollo.dl.playstation.net%2Fcdn%2FUP0367%2FNPUB31282_00%2F95PlZy1LVxrSFEHIybAGlZgwY4I7xNrV.png&sign=dfadf58fbced40e8ea4544b17ff3770b37f85c48","media_type":0,"productId":"UP0367-NPUB31282_00-ADVENTURETMGMPKG","release_date":0,"runtime":0,"salesType":"own","startedStreaming":false,"year_release":0},"entitlement_type":2,"feature_type":0,"game_meta":{"name":"Adventure Time: Explore The Dungeon Because I DON'T KNOW!"},"id":"UP0367-NPUB31282_00-ADVENTURETMGMPKG","inactive_date":"2015-04-20T04:49:36Z","is_consumable":false,"license":{"entitlement_id":"UP0367-NPUB31282_00-ADVENTURETMGMPKG","feature_type":0,"infinite_duration":true,"start_date":"2015-04-20T04:49:36Z"},"preorder_flag":false,"preorder_placeholder_flag":false,"product_id":"UP0367-NPUB31282_00-ADVENTURETMGMPKG","revision_id":1346780545918,"sku_id":"UP0367-NPUB31282_00-ADVENTURETMGMPKG-U002","subs_flag":false,"use_count":0,"use_limit":0}"

Looks like something to do with an Adventure Time game? I used the number 4983 as my starting point as you suggested.

**Comment by RePod** [comment]
I apologize, I quickly realized the command I gave you was wrong as PSDLE sorts its list before processing the Catalog.

Instead, I added a logging command which spits out what ID PSDLE is processing in that instance.

Please execute [this](https://gist.githubusercontent.com/RePod/e6d4c892ff3a76ac1a58/raw/5a1a331fa80235166278b0a90bd33763f49d9646/psdle.js) in the console (all of PSDLE with this extra logging command) in the console and run with Catalog enabled.

You should see a few `game_api->process pid_cache GAMEID` for a short while before it moves onto processing the games. Afterwards it'll switch to the actual games with represented by numbers:  `game_api->process 62 GAMEID`.

In theory whatever it dies on (or perhaps the last 5-10 numbers before dying) will be the culprit.

**Comment by JohnRoc** [comment]
>game_api->process 4975 UP1024-NPUB30142_00-0000000000000022
game_api->process 4976 UP1024-NPUB30142_00-0000000000000010
game_api->process 4977 UP1024-NPUB30142_00-0000000000000009
game_api->process 4978 UP1024-NPUB30142_00-0000000000000008
game_api->process 4979 UP1024-NPUB30142_00-0000000000000007
game_api->process 4980 UP1024-NPUB30142_00-0000000000000006
game_api->process 4981 UP1024-NPUB30142_00-0000000000000005
game_api->process 4982 UP1024-NPUB30142_00-0000000000000004
game_api->process 4983 UP1024-NPUB30142_00-0000000000000003
game_api->process 4985 UV0001-NPVA14670_CN-0000000000027045

It stopped at item 4983/5584 this go round. The final error was that same "e is undefined." Hope this helps, and thank you for trying to help me.

**Comment by RePod** [comment]
The last ID, `UV0001-NPVA14670_CN-0000000000027045`, seems to be for [the movie 2012](https://store.playstation.com/#!/en-us/movies/2012/cid=UV0001-NPVA14670_CN-0000000000027045), which clearly shouldn't even be considered for PSDLE.

Please run `repod.psdle.debug.entitlement("UV0001-NPVA14670_CN-0000000000027045")` in the console and post the results here.

**Comment by Effloresce** [comment]
Hey. I've got exactly the same problem. Works fine unless I select "Catalogue" too. I tried the troubleshooting mentioned in the previous messages. It stops at number 420 for me. If I run with logging, I get these as the last few:

> game_api->process 417 EP9000-CUSA00003_00-DCXLIVERIESXX018
> game_api->process 418 EP9000-CUSA00003_00-DCXLIVERIESXX017
> game_api->process 419 EP9000-CUSA00003_00-DCXLIVERIESXX015
> game_api->process 420 EP9000-CUSA00003_00-DCXVEHICLEXX0789
> game_api->process 422 EP0001-CUSA02900_00-GROWHOMEPS4SCEE0

Running the follwoing command in the console: repod.psdle.debug.entitlement("EP0001-CUSA02900_00-GROWHOMEPS4SCEE0") just gives this message: undefined

Any help would be great, as it's an awesome tool. Thanks!

**Comment by RePod** [comment]
Please try running [this version](https://raw.githubusercontent.com/RePod/psdle/638a309d93ba0bdb295207335c87b97e65acab3e/psdle.js) of PSDLE.

To execute it, try one of the following:
 - Paste this in your address bar: `javascript:$.getScript('//raw.githubusercontent.com/RePod/psdle/master/psdle.js');void(0);`
  - Ensure the line begins with `javascript:` before submitting.
  - This option will not work in Chrome.
 - Paste it in the browser console (Firefox: `Ctrl+Shift+K`, Chrome: `Ctrl+Shift+J`)
 - Paste it in the scratchpad (Firefox: `Shift+F4`) then click `Run`

Alternatively, if using the userscript you can [update it](https://github.com/RePod/psdle/raw/master/psdle.user.js).

**Comment by Effloresce** [comment]
Thanks for the speedy reply. Just tried it and it no longer hangs and ran to completion :) Thank you!

**Comment by RePod** [comment]
Nice, going to assume this fixes the original problem too.

The site's versions and the Chrome extension have been updated if you were using either.
