### ISSUE TITLE
Sort content by region code

### ISSUE THREAD

**Issue by Hyenard** [RePod/psdle#24]
Hi, thanks again for PSDLE, it helped me a lot during the past months.

I wonder if it'll ever be possible to sort all content "by region code" (since you can see them by moving the mouse over the name of the content), searching for different content for the same game (bought in different days/weeks/months or even years) in a Catalog with thousands of entries can be quite sluggish sometimes. I know there's a search function but not all content is named after their respective games.

**Comment by RePod** [comment]
You mean by the SKU/Product IDs? Seems kind of arbitrary.

**Comment by Hyenard** [comment]
Yes i meant that. Even searching by ID would be great, if you know them (by looking at internet databases, savegame folders or game cases lol)

Like i said not all items in the Store and Download List have the name of the games associated to them.

**Comment by RePod** [comment]
As your first line points out, "if you know them", it'd be a very obscure feature that I can't see many people using.

However, something similar is already available in PSDLE. It's a bit more hands on and requires using the [browser console](https://github.com/RePod/psdle/wiki/Gathering-Debug-Information#opening-the-browser-console). (not possible on Userscript)

`repod.psdle.debug.entitlement("123456-123456789_12-1234567891234567","id")` will search for the ID (*not product ID*) given and log matches. Can be partial.
