### ISSUE TITLE
Add game title as an extra field to the export area

### ISSUE THREAD

**Issue by oldmario** [RePod/psdle#26]
some dlc are labeled as dlc pack 1, dlc pack 2,dlc pack 3 or just character names and don't contain the name of the title they're from, any chance of adding this into the export area please?

**Comment by RePod** [comment]
Would require storing additional data to start off with.

I don't know how exactly this information is stored in Catalog API but I'll look into it.

**Comment by RePod** [comment]
Well, I finally looked into it (for your patience the latest PSDLE has new searching options).

It seems the Catalog has a "title_name" attribute that stores the base game's name (not the item's name), probably.
I only looked at a few items (Sword Art Online DLC and a Danganronpa theme, for Vita) and noticed this behavior.

I could make a testing implementation for you to try and see if that's what you're aiming for.

**Comment by RePod** [comment]
This is nearing completion due to a [new export window](https://cloud.githubusercontent.com/assets/7897871/14037563/ecaeccca-f21b-11e5-9370-b7d7e7d58ad0.jpg).

Expect a complete solution soon, as I need to determine the best way to find the parent's name.
As stated above, I can look at similar product IDs or use the Catalog. I may end up using either based on if Catalog is enabled.

**Comment by Tyrael87** [comment]
Hi, any progress on this?

**Comment by RePod** [comment]
Not particularly.
Still need to sit down and figure out exactly how I want to do this instead of just rough ideas.

**Comment by RePod** [comment]
As of 5ed936b34e3dbce2276013769c00684903837870, I believe this is done.

You can also now search by base game if desired.
However, entries without a proper parent/base game will be hidden by default if doing so.

----

***Technical stuff:***

The Catalog provides a `title_name` which *usually* (there are some exceptions) contains the parent/base game of the content. As such, this is now stored in the `baseGame` property and readily available for exporting.

For items that do not have Catalog entries, they do not get a `baseGame` property and are excluded from the search scope. In the future, it may be worth doing a reverse-lookup (with PSDLE's ID/PID caches) to determine parents.
