### ISSUE TITLE
Regarding Product ID and export

### ISSUE THREAD

**Issue by TetraMX** [RePod/psdle#27]
Hi, thanks for finally adding an option to search for content by Product ID (but what's the difference with Item ID?), now it's easier to search for all content for a specific game (although it's not 100% perfect, but it's not your fault: for example all Ridge Racer 7 DLC but one have a Japanese region code).

My question is: do you think it's possible to add an optional field to export this useful information? For example everything after "cid=EP####"

Also, do you think it's possible to add an option for PSDLE to remove stuff from the queue (just like it does on the "official" queue), or to disable PSDLE without having to refresh the page? (IIRC it wasn't even possible to do the refresh until a few versions ago, so thanks for that... unless i'm wrong)

**Comment by RePod** [comment]
>Hi, thanks for finally adding an option to search for content by Product ID (but what's the difference with Item ID?)

Item IDs are for the individual... items. Basically things that share a product ID (the base content).

For example: Telsagrad is cross-buy between PS3/4/Vita and they all share the same product ID `UP4513-PCSE00814_00-TESLAGRAD0000001`. However, they each have different item IDs to uniquely identify them.

Mind you, I make up this terminology in a way I understand and hope people will understand based off what I see the store doing.

>do you think it's possible to add an optional field to export this useful information? For example everything after "cid=EP####"

Anything is possible. However, this seems similar to issue #26 except just with the raw IDs.
However, your version would favor two rows more for product and item IDs.

>do you think it's possible to add an option for PSDLE to remove stuff from the queue

Unless it's broken, this should already be possible by clicking the desired item to remove from the queue.

I don't actually use the queue much but I can look into it.

>disable PSDLE without having to refresh the page?

I don't trust myself with reliably cleaning up PSDLE's residue. A refresh is guaranteed 100% clean.
However, browsers may have weird refresh behavior so Ctrl+F5 (hard refresh) might help.

**Comment by TetraMX** [comment]
No worries, i only suggested that "refresh" thing because the web Store is a SLUGGISH mess. Anyway i didn't know that clicking on items in the PSDLE queue delete them, thanks for the tip. Now it's only missing a checklist or something to put multiple items at the same time, haha. Too bad it doesn't work like that on the official queue.

I was more interested in that "export" thing anyway. There are things that just can't be listed with their proper platform no matter if i enable Catalog or not (for example, PS1/PS2 titles listed as PS3, or cross-buy games for PS3 and Vita, listed as for Vita in both entries). Like i said it should stay optional, i.e. disabled by default.

**Comment by RePod** [comment]
People have been asking for a while to be able to export arbitrary data from PSDLE.
I have a few ideas that may be able to satisfy everybody, probably.

**Comment by TetraMX** [comment]
Good to know ;) thanks, i'll wait for them.
