### ISSUE TITLE
PS Plus (PS+) support.

### ISSUE THREAD

**Issue by RePod** [RePod/psdle#3]
At the time of writing this is currently being implemented (and pretty much working) and should be at shortly with an issue reference to here, however as I don't own a PS4 or have purchased PS4 games I can't test for those as much as I'd like to.

**What I need tested:**
1. False positives, specifically for **PS4**.
2. The opposite of that, PS+ games not marked as such.

Note some content may be available only through PS+ but you get to keep it forever (and isn't tied to the subscription afterwards), avatars are a good example of this.

Thanks!

**Comment by EvilCanasta** [comment]
Isn't this problem solved?

**Comment by RePod** [comment]
I only have my own list to test off so I'll leave this open on the off chance somebody encounters a problem.

**Comment by EvilCanasta** [comment]
Well at least that problem with the EA titles for PS 20th Anniversary was solved. Maybe i'll check all my PS+ games one by one, since it's a different country and mine has always more problems.

**Comment by Hyenard** [comment]
Any news on this?

**Comment by RePod** [comment]
Probably going to close it soon.

This was more of an issue between September and early December 2014. Since then I rewrote list generation and PS+ status of items is very accurately detected, aside from #17.

But if I close this I'll have to update a bunch of references to it, and I'm lazy.

**Comment by Hyenard** [comment]
Well you closed the other so you're going to close this one too, right? :P

**Comment by RePod** [comment]
![a](https://cloud.githubusercontent.com/assets/7897871/8368230/8ea6b2aa-1b75-11e5-8d1e-d777e6262d64.jpg)

**Comment by Hyenard** [comment]
I'm seeing it at PS+ o_o i have two entries, one with a size  (14.7GB) and one without (i guess that's the license "key")

**Comment by RePod** [comment]
![screenshot_3](https://cloud.githubusercontent.com/assets/7897871/8368327/cb03144a-1b76-11e5-85a0-eaadfc50c356.jpg)

Beats me. For now.

**Comment by Hyenard** [comment]
Yeah i noticed that the description of the game soundes like a "temporary trial". I don't even know where it is under Account Management hahah (probably it's the first DLC i've ever obtained, i'll have to search)

**Comment by Hyenard** [comment]
Talking about PS+, shouldn't the PS+ checkbox be enabled by default in the "Export View" screen? I mean who doesn't have PS+ today (especially on PS4), and all the others are already checked.

**Comment by TetraMX** [comment]
Hi, i think PvZ is not marked as PS+ anymore, while Driveclub PS+ Edition is. Like it should be.
