### ISSUE TITLE
Catalog + Language selector

### ISSUE THREAD

**Issue by alexdlc** [RePod/psdle#31]
Would be really great if we could hide anything thats not a game. Or at the very least, if things were labeled as games or as themes.

**Comment by RePod** [comment]
Have you enabled Catalog during startup?

**Comment by alexdlc** [comment]
During startup? I'm using the Chrome add-on.

**Comment by RePod** [comment]
Before you press "Start".

**Comment by RePod** [comment]
![catalog](https://cloud.githubusercontent.com/assets/7897871/14961536/0c625400-1068-11e6-9b2c-5e0b33f1e9ef.jpg)

**Comment by alexdlc** [comment]
Oh, I must have missed that. Just tried it, and it does help, but for some reason, some games are 'unknown'. Also some themes still show up if I disable themes. I guess thats just a problem with the PS Store and not with PSDLE.

**Comment by RePod** [comment]
Correct, PSDLE uses the same information the store provides and cannot do anything about it.

**Comment by alexdlc** [comment]
Alright, thanks for the help. Got another problem, should I open it as a new issue?

**Comment by RePod** [comment]
Here is fine.

**Comment by alexdlc** [comment]
Ok, I noticed in the start screen I can choose language, but I cant choose english. Is this normal behavior because I live in Spain? It shows 'Español [en-us]'

**Comment by RePod** [comment]
Is the interface in English despite that, or Spanish?
I assume your problem is that you want to use it in English but cannot since it's not selectable (or in your case "is" but is not working and labelled improperly)?

By default PSDLE tries to select the "best" language in three steps:
 - Region + language (for *en-??*, it'll use the *??* from *en* if it can)
 - Region (if it can't find *??* it'll use *en*'s default which is *us*)
 - Then just *en-us* (if it can't figure out the above two)

For it to resolve to Spanish means your default store country is *es* plus the language's identifier which PSDLE doesn't have thus it uses *es-es* since it's the first .

Unfortunately, despite my best efforts, I've never been able to nail down all problems with the language selector. Guess one more try won't hurt.

**Comment by alexdlc** [comment]
If I select 'Español [en-us]' it is still in Spanish. It's not a big problem since I know both Spanish and English, but I just prefer english.

**Comment by RePod** [comment]
What happens if you select other languages and/or select it again after doing that?

**Comment by alexdlc** [comment]
If I choose Spanish, it's in Spanish, If I choose French, it's in French. If I choose German, it's in French still. And if I choose Russian, its also in Spanish.

**Comment by RePod** [comment]
Well, the good news is I found the problem and it's interesting that I can finally fix it.

Spanish was being copied over English, so it you were setting it to *en-us* but with Spanish's information.

**Comment by alexdlc** [comment]
Cool, glad I could help.

And btw, thanks for making this, It's really useful! ;)

**Comment by RePod** [comment]
I have a few more changes I want to get in before I push this live across all versions, however you may test this fix now.

To try it:
 - Open the webstore as usual but don't activate the Chrome extension.
 - Open Chrome's console by pressing *Ctrl+Shift+J*
 - By default, the text input will be ready to go
 - Paste the contents of [this URL](https://raw.githubusercontent.com/RePod/psdle/e88d6b6b8fb9158f8294cb9749e54746f92b2fbc/psdle.js) (all of PSDLE) into it and submit
 - PSDLE will run as normal

**Comment by RePod** [comment]
I've gotten my small changes done and have pushed this fix to all versions available from the site.

It may take up to an hour (according to the store) for version 1.50 of the Chrome extension to be available, at which point you may manually reinstall it or wait for Chrome to update it automatically. However, all other versions can be used immediately.

Thanks for the bug report, please consider leaving a review for the Chrome extension and/or checking the "Support PSDLE" section on the website!
