### ISSUE TITLE
Cannot Export "Size" or "Index" columns

### ISSUE THREAD

**Issue by ConsoleChairman** [RePod/psdle#34]
Browser: Chrome Version 53.0.2785.116 m
Method: Chrome Plugin (v 1.58)
Online store version and language: Desktop, en-us
Problem: I have 656 entitlements and I'm toying with exporting them, if I only do a few columns then the export works fine but once I select about half of the available columns and choose export, I'm prompted for a delimiter and then nothing happens, the column/property mapping modal popup never disappears and the delimited list of...everything, never appears.

**Comment by ConsoleChairman** [comment]
Further testing, I limited my view down to a single title and specified every column. I chose Export View and specified semicolon (;) as my delimiter. The modal still did not disappear. I did not interact with my browser in any way for 5 minutes so that I wouldn't accidentally interrupt anything and in that time the modal never disappeared and the export never displayed.

**Comment by ConsoleChairman** [comment]
After even more testing, narrowing down to a single result and a single column, I can neither export Size, nor Index, but all other columns specified in any arrangement, even with my full library, export fine. Changed the issue name for accuracy.

**Comment by RePod** [comment]
Nice catch.

Seems the problem was a string-type function was a being called on them, but since they were numbers (and not strings) the function would fail!

All versions should reflect the fix, but the Chrome extension may take one to a few hours to process and be available.
