### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by k0ta0uchi** [RePod/psdle#36]
Hi devteam!

I have translated PSDLE into Japanese language.
Please see attached txt file.

Thanks,
Kota
[psdle-ja-jp.txt](https://github.com/RePod/psdle/files/792348/psdle-ja-jp.txt)

**Comment by RePod** [comment]
Thanks!

The Chrome version may take up to 60 minutes to reflect (version 1.62) as of this reply, all other versions should have it immediately.
