### ISSUE TITLE
'Export view' not working.

### ISSUE THREAD

**Issue by slashbeast** [RePod/psdle#37]
Hi, I cannot get 'Export view' to work. When I click it nothing happens and nothing goes to console. I tried with userscript on Firefox and Chrome extension, the same outcome - nothing

Store language is English (en-pl).

**Comment by RePod** [comment]
Sorry for the inconvenience, the fix should be live on all versions except the Chrome extension which will take up to one hour as of posting to update.

**Comment by slashbeast** [comment]
Many thanks
