### ISSUE TITLE
Group DLCs per game

### ISSUE THREAD

**Issue by wormangel** [RePod/psdle#38]
Hi, great work on this lib, I've been searching for a PSN API or something like that in order to build a similar tool like PSDLE, thanks!

Is it possible to infer the game to which a DLC ("Add-On") belongs to? It would be really cool to have a way to choose a game on your lib and then see the list of DLC you have for that game.

Unfortunately sometimes PSN give false alerts: I was checking a bit in the console and saw for example that "The Bitter End by Placebo" (contentId `UP0002-BLUS30164_00-PGUITARHER000155`, DLC for Guitar Hero World Tour) is categorized as `GAME`, even though is a DLC; went to check in the store itself, it's actually not available anymore.

Then I checked "DOA5LR Costume Catalog LR45" (productId `UP4108-CUSA01665_00-CATALOGSEASON460`, DLC for Dead or Alive 5 Last Round), it doesn't have a `contentType` set but both PSDLE and the store label it as Add-On, and the store displays it as an add-on to Dead or Alive 5 Core Fighters.

So it seems it might be possible to come up with something? I'd gladly try contributing after you give me your initial thoughts :)

Thanks!

**Comment by wormangel** [comment]
OK, I've shot the gun here - just saw you can search by base game (and it works for the Guitar Hero one too, cool).

I was going to edit this ticket to change it to an UI improvement suggestion (selecting a game and in the game details box that opens - or some other form of UI popup - seeing all the DLC you have for that game), but I think I'll just play around with the code and maybe open a PR.

Thanks again!

**Comment by RePod** [comment]
Regex searching lets you get pretty specific.

[See this page on the wiki.](https://github.com/RePod/psdle/wiki/Enhanced-Filtering#searching)
