### ISSUE TITLE
Nothing in PSDLE list showing after date 11/21/2016

### ISSUE THREAD

**Issue by drd7of14** [RePod/psdle#44]
Just went on to export a new list with some titles I had recently purchased as apart of the Black Friday sales.

Low and behold, nothing will populate past the date 11/21/2016.  Try changing filters, switching between PLUS/Non-PLUS/Both, yet nothing seemed to change.

All platforms are populated in the list, PS1, PS2, PSP, PS3, PSV, PS4, and PS2 on PS4 all show up in the list, just nothing after said date 11/21 date.

Not sure if this is related to the Valkyrie API update or not, but I figured I'd add my input and see if there is a fix.

![capture](https://user-images.githubusercontent.com/33640161/33402504-c1e8d67c-d52a-11e7-97d5-8267bccf1809.JPG)

**Comment by RePod** [comment]
Please run [this version of PSDLE](https://raw.githubusercontent.com/RePod/psdle/9499d1f67291d481be6288bdfbc1602e3b3498bc/_src/psdle.includes.js) by copy-pasting the contents of the URL into your browser's console (Firefox: Ctrl+Shift+K, Chrome: Ctrl+Shift+J).

Do not activate any other method of PSDLE while doing this.

**Comment by drd7of14** [comment]
Thanks,

I tried that test code in the console on Chrome, and it populated properly.

No issues, even tried it twice just to verify.  I have over 3000 items, so it takes a while to load.


I was using version v3.1.5 of the PSDLE extension in Chrome.

    On Wednesday, November 29, 2017, 6:11:03 PM EST, RePod <notifications@github.com> wrote:  
 
 
Please run this version of PSDLE by copy-pasting the contents of the URL into your browser's console (Firefox: Ctrl+Shift+K, Chrome: Ctrl+Shift+J).

Do not activate any other method of PSDLE while doing this.

**Comment by RePod** [comment]
Good to hear.

I've pushed all versions to 3.1.6 with the fix, however the Chrome extension may take up to an hour from this reply to appear on the webstore.
