### ISSUE TITLE
[suggestion] Export View: change default properties and column names

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#45]
It would be great when the default properties for "Export View" would be changed to:
1. Platform = platform
2. Name = name
3. PKG direct link = pkg
4. Content ID = id
5. File Size = size
6. Date = date

As the current default is missing some interessting data (size but no link) and the prettied output can lead to issues when importing into a calculation sheet.

The current defaults are fine for the displayed list inside the browser, but they are not perfect for exporting as CSV/JSON.

Would be much appreciated.

**Comment by RePod** [comment]
Your concern is valid and your reasoning is fine (specifically the part about current defaults which mirror the list). However, I'm not changing the defaults as I feel they cover most user's interests. Instead I've added two new features to the export window:
 - The ability to move a row up from where it currently is
![2017-12-31_13-12-38](https://user-images.githubusercontent.com/7897871/34463520-5d458182-ee2c-11e7-9975-ff850b48827c.gif)
 - The ability to export the config and easily import it back to allow easier sharing of "presets"

---

While it is possible to store the export config to use the next time PSDLE is run the store itself relies on that available storage more than PSDLE does so I would rather not impact it. This stance may change in the future, but not now.

The new features are available in version 3.1.9, released immediately. The Chrome version may take up to an hour to be available.

**Comment by windsurfer1122** [comment]
That's so great and easy to use.
Just define once, click "Import", copy as template and re-use with "Import" the next times.
Thanks a lot.
