### ISSUE TITLE
Inject Language broken: TypeError: repod.psdle.genDisplay is not a function

### ISSUE THREAD

**Issue by Gnarmagon** [RePod/psdle#49]
Browser: Chrome
Method: Extension
Online store version and language: Desktop, de-de
PSDLE version: 3.2.1
Monkey variant: not installed ?
Is Catalog enabled: No
Problem: TypeError: repod.psdle.genDisplay is not a function
How to replicate: open https://store.playstation.com/, start psdle, inject lang, enter for example this json: https://pastebin.com/H6G8HpcK (from psdle/_src/lang/all/en.json)
Other notes: ![image](https://user-images.githubusercontent.com/24826124/38024741-2668506a-3286-11e8-85c4-e0d3ff14139c.PNG)

**Comment by RePod** [comment]
Should be fixed in 3.2.2

**Comment by Gnarmagon** [comment]
It's working now :)
