### ISSUE TITLE
Nothing shows up in the list

### ISSUE THREAD

**Issue by azumukupoe** [RePod/psdle#52]
![SS1](https://screenshotscdn.firefoxusercontent.com/images/2a069656-0fae-41a1-a1b2-08141e91d75d.png)
![SS2](https://screenshotscdn.firefoxusercontent.com/images/fefb7e42-8faf-43f3-a39a-d4ca66d058c4.png)

**Comment by RePod** [comment]
Signed in?

**Comment by azumukupoe** [comment]
@RePod yes

**Comment by RePod** [comment]
Console messages? Chrome: Ctrl+Shift+J, Firefox: Ctrl+Shift+K
![firefox_2018-03-30_01-56-42](https://user-images.githubusercontent.com/7897871/38126293-a8fec45e-33bd-11e8-8adb-11f2d3f68f67.png)

**Comment by azumukupoe** [comment]
@RePod 
![default](https://user-images.githubusercontent.com/31339007/38126442-a4a64396-342b-11e8-8554-55ca3ebde3d9.PNG)

**Comment by RePod** [comment]
Does refresh fix it? If not, please provide this as attachment unless it is empty.
![firefox_2018-03-30_02-08-08](https://user-images.githubusercontent.com/7897871/38126530-3bfbdcaa-33bf-11e8-9d8c-c64f3c0e0447.png)

**Comment by azumukupoe** [comment]
[psdle_2018-3-30 15-11-11_raw.zip](https://github.com/RePod/psdle/files/1862802/psdle_2018-3-30.15-11-11_raw.zip)

**Comment by azumukupoe** [comment]
Weird, it seems to work now.
It might have been a problem with them.

**Comment by RePod** [comment]
Might be a separate problem too. I'll continue looking into it.
![firefox_2018-03-30_02-24-00](https://user-images.githubusercontent.com/7897871/38126910-867dc782-33c1-11e8-9c0b-9c696fc15005.png)
