### ISSUE TITLE
Unable to add downloads to queue

### ISSUE THREAD

**Issue by nutron** [RePod/psdle#54]
Clicking on an item brings up the artwork and the option to download to your PS3, Vita, or PS4.  When clicking on the "download to your console" button, nothing seemingly happens.

Shift+Click on the list brings up an error from the store that says:

There is no available target console to send to.

I have confirmed that going through the store still works just fine and have added downloads to my queue via that method.

**Comment by RePod** [comment]
Should be fixed as of version 3.2.9, or if you enabled Catalog during startup.
The Chrome and Firefox extensions may take an hour or so to receive the update.

**Comment by RePod** [comment]
Going to assume this is fixed then.

Was a small leap in logic caught in the move to container generation.
