### ISSUE TITLE
Catalog Filtering Broken When Hiding PS+ Titles

### ISSUE THREAD

**Issue by ConsoleChairman** [RePod/psdle#55]
**Browser:** Chrome 66.0.3359.170 64-bit
**Method:** Extension
**Online store version and language:** Desktop, en-us
**PSDLE version:** 3.2.9
**Monkey variant:** N/A
**Is Catalog enabled:** Yes
**Problem:** Disabling Catalog filters (e.g. Games, Add-ons, Themes) does not remove matching results when filtering out PS+ titles or showing only PS+ titles. (Works as intended when showing all)
**How to replicate:** 
- Run PSDLE and choose Purchase History and Catalog
- Once the list appears, click the [-] symbol to switch from "show all" to hiding PS+ titles (checkbox will now be empty)
 - Try to filter by any of the filters on the second row. The list will refresh, but no items matching the disabled filter will be removed

**Other notes:** none

**Comment by RePod** [comment]
Confirm if the problem exists in version 3.3.0.

**Comment by ConsoleChairman** [comment]
No longer able to reproduce, appears to be resolved as of 3.3.0.
