### ISSUE TITLE
Extension doesn't activate in FireFox 52.7.3 x64

### ISSUE THREAD

**Issue by DeepMac** [RePod/psdle#56]
I installed the FF extension just today but it will not activate. It's enabled, but after navigating to the PSN Download List, no PSDLE logo appears anywhere. Nor does it appear when accessing the main Playstation page.

Numerous error messages are reported in FF console that appear to be related to the extension, and indicate issues with the API:

```10:49:23.670 [GCT] Deprecation Notice:
"telemetryService.eventAccess" has been marked as deprecated as of 2018-03-21.
## Important Dates
Exception Thrown: PSI 19 (2018-08-30).
The exception can be temporarily overridden using the key: "allowTelemetryServiceEventAccess".
Feature Removal: PSI 20 (2018-12-06).  vendor-e2bff3e131d9c9f9827e57706ec6fc39.js:23:28627

10:49:23.675 [GCT] Deprecation Notice:
"config.events.name" has been marked as deprecated as of 2018-03-21.
## Important Dates
Exception Thrown: PSI 19 (2018-08-30).
The exception can be temporarily overridden using the key: "allowConfigEventsByRegistryName".
Feature Removal: PSI 20 (2018-12-06).  vendor-e2bff3e131d9c9f9827e57706ec6fc39.js:23:28627

10:49:27.834 Unable to attain user listId  valkyrie-storefront-59e330aafc0e35b37e6fdeec1b818ca0.js:27:30400

10:49:29.554 [GCT] Length of major exceeds 16 chars limit for: 'tag-manager-service'  vendor-e2bff3e131d9c9f9827e57706ec6fc39.js:23:28627

10:49:30.518 The following strings need to be removed from app/pending-strings.js: vc.page.voucher.redeem.expired,vc.voucher.expired  transact.playstation.com:30917:5
```

**Comment by RePod** [comment]
If that's one of the ESR releases I'm not sure, but the minimum required is Firefox 57+.
The log provided was generated entirely with the store, nothing there is PSDLE.

For pre-57 Firefox use either the Userscript or Bookmarklet for single-click access.

**Comment by DeepMac** [comment]
Yes, it's the ESR release. The Userscript version works fine with Greasemonkey 3.1.7 under this version of FF.

If the extension requires FF 57+ then it shouldn't be possible to install it under FF 52. I assumed since it installed it was compatible. I think that just requires adjusting the metadata for the extension on the Addons page.

Thanks for PSDLE, BTW. Exactly what I was looking for!

**Comment by DeepMac** [comment]
I think you have to. Looking at the PSDLE page and the page for Kee, the one for Kee disables the "Add to Firefox" button and displays a banner saying the add-on requires a newer version of FF. And the manifest would also prevent even manually installing the add-on to an incompatible browser.

Should eliminate future support headaches too, :)

**Comment by RePod** [comment]
Guess we're set then, thanks for the report!

![firefox_2018-05-29_17-34-59](https://user-images.githubusercontent.com/7897871/40686833-a36a8b80-6366-11e8-9a84-01fd26ddbcca.png)
