### ISSUE TITLE
Filter for PSVR titles

### ISSUE THREAD

**Issue by silentnoodlemaster** [RePod/psdle#57]
Currently VR games have PS4 as their platform, which is indeed correct so this might not even be possible?

**Comment by RePod** [comment]
Definitely possible. The same way the store presents them, PSDLE can detect them with Catalog:
![ff1](https://user-images.githubusercontent.com/7897871/43088622-980bbc52-8e70-11e8-84ce-755d91c64bdd.png) ![ff2](https://user-images.githubusercontent.com/7897871/43088656-b2495e26-8e70-11e8-9358-1a728acacd5c.png)

However it is currently in direct contrast in how they're presented in PSDLE which has the system platforms and, if Catalog is enabled, categories. The quick and easy solution would be how PS1 and PS2 classics (among PS3/4) are presented as their own system if Catalog is enabled. Also I have no PS2 Classics for PS4 on my account so I'm not sure even that is working properly for the download queue, but I assume PS VR in a similar fashion will not break.

If and when I get around to it, the result would be:
 - It will require Catalog enabled
 - It will be shown as a System and not a Category (which makes some sense)
![ff3](https://user-images.githubusercontent.com/7897871/43089094-d0d56c30-8e71-11e8-974c-038a81228767.png)

**Comment by RePod** [comment]
This feature has been added, please confirm it is working as of version 3.3.2.
It may take up to an hour for the Chrome version to receive the update, but every other version should be immediate.

**Comment by RePod** [comment]
![n](https://user-images.githubusercontent.com/7897871/43098512-549641a0-8e8d-11e8-9c1d-75622941d006.png)
These are the immediately accessible properties, so I chose to only check if "vr-compatibility" is "required"
Trackmania Turbo shows at least 3 states for each item: `incompatible`, `compatible` and `required`.

I could change the PS VR filter to include compatible *and* required, but I can see either side being confused:
 - PS VR owner who wants a game but not VR filters it out a compatible one.
 - Non-PS VR owner filters out a compatible one.
