### ISSUE TITLE
PSDLE JSON Export Bug

### ISSUE THREAD

**Issue by JK3Y** [RePod/psdle#59]
**Browser:** (Firefox 57/Chrome #/etc.)    
Brave
**Method:** (Direct/Userscript/Bookmarklet/Extension)    
Bookmarklet
**Online store version and language:** (Desktop/mobile) (en-us/de-de/etc)    
en-us
**PSDLE version:** x.x.x    
v3.3.4 2018-07-29
**Monkey variant:** (Greasemonkey/Violentmonkey/etc.) (if applicable)    
**Is Catalog enabled:** (No, by default/Yes)   
No

---

**Problem:** ~    
PSDLE exports one item and repeats the same item for the whole file.
**How to replicate:** ~    
Export view as JSON
**Other notes:** ~
<img width="1792" alt="screen shot 2018-11-09 at 2 15 13 pm" src="https://user-images.githubusercontent.com/17938577/48286325-ecf46880-e42a-11e8-946f-db3205206501.png">

**Comment by RePod** [comment]
Please use version 3.3.5.
