### ISSUE TITLE
PSP content issue

### ISSUE THREAD

**Issue by RandomGuyZ** [RePod/psdle#6]
Not sure when it happened but after version v1.038 (or v1032, i don't remember), the download list generated by this script has some issues with PSP content. While PS3/Vita/PS4 content is sorted properly, the PSP one is not. I obtained PSP content only in 2010/2011, but part of it is listed at the bottom, like it should be (my first PSN-era system was a PSP, i waited another 3 years to get a PS3), and another one is at the TOP of the list. I mean stuff from 2010/2011 appears as more recent than stuff added to my account in 2015. i.e. I see stuff from 2011/2010, then again 2015, 2014, 2013... etc., and again 2011 and 2010. If i disable the PSP content, all the other content is sorted properly. On a side note, all other PSP content in 2012 (and beyond) is sorted properly.

The script never ever had this issue before, like i said at the beginning of this message. Going back to a previous version is no longer an option as it no longer works, probably since last week, as it generates a list with just a small fraction of all my PSN content.

I've attached a screenshot. "DW Strikeforce" was my first content ever added to my PSN account, while "Collectors Edition" is the most recent one. It happens no matter which options i choose.

![aaaaa](https://cloud.githubusercontent.com/assets/10741436/5937953/25e33890-a6f6-11e4-95b6-8f582bcbdaa1.jpg)

**Comment by RePod** [comment]
Does manually sorting by "Date" (clicking the column title) fix this issue?

If so, this is a known issue that is currently on my to-do list. Basically the internal list PSDLE keeps isn't sorted initially, so as soon as I work that out this should be resolved.

**Comment by RandomGuyZ** [comment]
No, it doesn't. Thanks for replying though.

**Comment by RePod** [comment]
Just pushed userscript 2.009, please try it out. May need to force an update check in your Monkey variant.

If you're using the bookmarklet it should use the latest version.

**Comment by RandomGuyZ** [comment]
Yes, it seems to be all fine now with the new version. 

Thanks for fixing this issue, and for this wonderful userscript.
