### ISSUE TITLE
3.3.7: "Import"ing an unknown property for "Export View" disables Export

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#62]
**Browser:** Chrome

**Method:** Extension

**Online store version and language:** Desktop

**PSDLE version:** 3.3.7

**Is Catalog enabled:** Yes

---

**Problem:**
When "Import"ing an unknown property for "Export View", then PSDLE just returns to the list and "Export View" cannot be clicked anymore.

**How to replicate:**
Click "Export View"
Click "Import"
Enter [["PSDLE Category","category"]]  (note that the existing property "category" is on the wrong side, and that a property "PSDLE Category" does not exist)
Click "Ok"

**Other notes:**
First expected an error message like "Properties "PSDLE Category" do not exist and are skipped".
Second that unknown properties are skipped and "Export View" keeps useable.

**Comment by RePod** [comment]
Currently it operates silently like this:
![2019-01-04_15-36-42](https://user-images.githubusercontent.com/7897871/50709685-96746680-1036-11e9-985d-6871df689337.gif)
Feedback about the importance of the errors is welcomed.
Right now the only idea I'm confident with involves adding a new line to the translations, but I'm not against it or any alternatives.

**Comment by windsurfer1122** [comment]
An error message would help to recognize the problem immediately.
I got my property error from myself due to a copy&paste plus rename mistake inside my own notes :(

Does PSDLE fallback to English if the translation is missing? If so, then I would definitely add the error message.
Otherwise I would also be fine without an error message.

Thanks for reacting so fast.

**Comment by RePod** [comment]
The original fix described above (removing keys) has been pushed to live along with other changes.
Though still not presenting a dialog about removed keys they are currently logged into the browser console.

**Comment by windsurfer1122** [comment]
Shall we close this issue?
