### ISSUE TITLE
Suggestion: Get the cost of each item when exporting as JSON/CSV

### ISSUE THREAD

**Issue by NeoTechni** [RePod/psdle#65]
And calculate the total like you do the total filesize. That way we can see (aprox. since the prices will be a bit out of date) how much we've spent.

Though if PSN gives you the date of purchase you could use https://psprices.com/ to check the history of it and get the price at that time.

**Comment by RePod** [comment]
If Catalog is enabled there is a `displayPrice` property accessible in the export window which I believe is, unfortunately, the current price whatever it may be (possibly including sales).
I'm not sure about totaling them up unless the store has a function for it already (I'll have to check, maybe related to the cart), as that is how PSDLE totals sizes and returns a locale-aware format.
However, calculating totals should be possible in spreadsheet software.

---

As for third-party service integration there are three roadblocks:
 - There is no (publicly) accessible API and retro-fitting to support it is a nightmare. If the site or pages ever change that's something I have to fix, assuming it works up to that point.
 - In the interest of security and saving on tinfoil PSDLE has not and continues to not interface with anything except the store. 
 - PSDLE is very portable (runs wherever it can) and all versions share the same base version. The implementation would have be highly compatible which would most likely be limited by browser security policies for fetching off-site information. The Chrome and Firefox versions would require additional external code and the feature might not be possible at all on direct/bookmarklet/userscript.

I turned down Metacritic integration for mostly same reasons.

**Comment by NeoTechni** [comment]
displayPrice mostly worked (thank you), though it has 2 issues:
-How do I exclude PS+ titles? They artificially inflate my total to a scary amount ($17,000)
-Can you please make N/A show as $0 instead? (perhaps for a new column, actualprice) It messes with the math.

**Comment by RePod** [comment]
The item count above the list, before opening the export window, lets you toggle PS+ status between not/either/only and that carries over into the export window (along with other list options such as filters, search, and sort). A full list would require two exports (one with and without plus) or also exporting the `plus` property.
`N/A` is what the Catalog responds with and would differ between languages, so I'd rather leave it alone. A string replace in the spreadsheet software should suffice.

**Comment by NeoTechni** [comment]
Thank you. I wasn't able to find the PS+ status toggle, but I found the plus column.

**Comment by RePod** [comment]
![](https://user-images.githubusercontent.com/7897871/56870190-c971aa00-69d9-11e9-8827-2623c6aa3be1.png)

**Comment by NeoTechni** [comment]
Ah. Thank you again.
