### ISSUE TITLE
JSON Export: Remove ambiguity from "columns" objects

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#68]
**PSDLE version:** 3.3.10

---

**Problem:**
On a JSON export the "columns" array only includes string arrays.
```json
    "columns": [
        [
            "platform",
            "Platform"
        ],
```
Right now interpretation and programmers have to rely on the order of the strings, first "PSDLE property" then "column title".
My suggestion is to use objects rather than string arrays, so the meaning of each string is explicitly defined.
```json
    "columns": [
        {
            "property": "platform",
            "title": "Platform"
        },
```

**How to replicate:**
Just do a JSON export.

**Comment by RePod** [comment]
At the cost of breaking legacy support the import also reflects this change, but I would assume most users were not generating the import lines themselves anyway.

You may verify this [this version](https://raw.githubusercontent.com/RePod/psdle/894a2b2c3536b5c35a6f1eaf447d40a18ac33f11/_src/psdle.includes.js) if you want (run in your browser's developer console).
Regular export, JSON, and CSV should all be fine.

If there are no complaints then I'll push this live.

**Comment by windsurfer1122** [comment]
Other suggestion: Add a string "version" to the very top of JSON.
This way developers know...

- No version, then PSDLE <= 3.3.10 and therefor string arrays
- Version stated, then act on known changes to the JSON format

How about this?

**Comment by RePod** [comment]
The JSON will now have a `version` property at the top level and regular export/CSV will have it in the last column of the last row (surely nobody will ever ask me to standardize this) following the column with the stringified export config.

A crude example of CSV:
```
Name,System,Date
A,B,C
name,platform,prettyDate,[{config}],4.2.0
```

I proactively split the version number and compile date (which previously contained HTML formatting) and am including only the version on export.

New testing version [here](https://raw.githubusercontent.com/RePod/psdle/bf271200500d4e6b0d4f2d1d2b6ee7b0a7c201a5/_src/psdle.includes.js).

**Comment by windsurfer1122** [comment]
Looks really good too me.

```json
{
	"version": "3.3.13",
	"columns": [
		{
			"property": "platform",
			"title": "Platform"
		},
		{
			"property": "category",
			"title": "PSDLE Category"
		},
		{
			"property": "platformUsable",
			"title": "Platforms Useable"
		},
	],
	"items": [
		{
			"platform": "PS4",
			"category": "Juegos",
			"platformUsable": [
				"PS4"
			],
		},
	]
}
```

**Comment by windsurfer1122** [comment]
Don't forget to add a small note to the changelog and to the readme that developers haver to check for the "version" string in a JSON first, then act on its missing or value:

- No version, then PSDLE <= 3.3.10 and therefore string arrays
- Version stated, then act on known changes to the JSON format

**Comment by RePod** [comment]
The only release version that has a change log is the Firefox add-on, but I'll put a note at the top of the repository readme in case people arrive to complain.

I'll also make a bug reporting template about it just in case.

**Comment by JK3Y** [comment]
Hello, building on top of this, would it be possible to (when exporting as JSON) have the property name be the camelCase version of the column name?
for example:
`
{
  property: 'id',
  title: 'Content ID'
},
{
  property: 'size',
  title: 'File Size'
}
`

will output:
`
{
  contentId: <PSDLE 'id' property>,
  fileSize: <PSDLE 'size' property>
}
`
This way the title property can still be utilized on JSON exports. CSV exporting will remain unchanged.

**Comment by RePod** [comment]
I would be fine with normalizing the property names themselves with some feedback.

Dynamically changing the property on export seems a bit too broad. I'm having trouble understanding the advantage.

**Comment by JK3Y** [comment]
Currently in my use-case I'm mapping through the objects and essentially duplicating the property into the one that follows my the naming conventions used in my own code:

```
items.map(item => {
  item.contentId = item.id
  item.url = item.pkg
  item.fileSize = item.size
})
```
