### ISSUE TITLE
When in the "Export View" definition, then deleting removes always the last line

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#69]
**Browser:** Chrome 74.0.3729.169 x64 Win

**Method:** Extension

**Online store version and language:** Desktop, en-gb

**PSDLE version:** 3.3.10 (and test of 3.3.13)

**Is Catalog enabled:** Yes

---

**Problem:**
When defining the columns for the export view, there the "minus symbol" always deletes the last line and not the line the cursor is/was currently on.

**How to replicate:**
- Run PSDLE
- Goto "Export View"
- Place cursor on the first(!) line
- Click "minus symbol" --> and the last line vanishes

**Other notes:**
If this is to complicated to realize inside browsers, then just close this issue.

P.S.:
Same also applies to the "plus symbol", but that's not a real issue as nothing gets lost and the new entry can still be moved up to its final position.

**Comment by RePod** [comment]
Adding and removing from the bottom of the list is intended with the current setup.

You also can't remove past the last remaining line for this reason.
