### ISSUE TITLE
Exporting 4000+ titles gives download error in Chrome

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#70]
**Browser:** Chrome

**Method:** Extension

**Online store version and language:** Desktop

**PSDLE version:** 3.3.13

**Monkey variant:** n/a

**Is Catalog enabled:** Yes

---

**Problem:**
Download fails when exporting more than 4000+ titles.
Chrome gives an download error.

**Workaround:**
Toggling off some platforms to get under 3000 titles.
But soon this won't be enough anymore.

**How to replicate:**
Export 4000+ titles with the following properties
[{"property":"platform","title":"Platform"},{"property":"name","title":"Name"},{"property":"pkg","title":"PKG direct link"},{"property":"id","title":"Content ID"},{"property":"size","title":"File Size"},{"property":"baseGame","title":"Alternate Name"},{"property":"productID","title":"Product ID"},{"property":"url","title":"Store URL"}]

**Other notes:**
If this is a browser limitation (memory, etc.), maybe then split up in chunks of 1000s.

**Comment by windsurfer1122** [comment]
Exporting these 4000+ titles works fine on Firefox.

**Comment by RePod** [comment]
Try [this version](https://gist.githubusercontent.com/RePod/4cb04cafffb2f976df6c9bcb7f7a7113/raw/3356f9992a1336b97c172a35e6b20c9cab14a4a5/psdlenowwithblobs).

**Comment by windsurfer1122** [comment]
Works in Chrome. Returned the same result as PSDLE 3.3.13 in Firefox.

**Comment by windsurfer1122** [comment]
If you tell me how to test in Firefox, then I will do this too.

**Comment by windsurfer1122** [comment]
Any chance to get this into the official release soon. Still willing to test in Firefox, if shortly explained how.

**Comment by RePod** [comment]
Both #70 and #71 have been pushed as 3.3.14

**Comment by windsurfer1122** [comment]
Thanks for your awesome support- Much appreciated.

**Comment by windsurfer1122** [comment]
3.3.15 works well on Firefox with 4400+ titles
