### ISSUE TITLE
Use ISO 8601 combined date and time for download file name

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#71]
**Browser:** Chrome

**Method:** Extension

**Online store version and language:** Desktop

**PSDLE version:** 3.3.13

**Monkey variant:** n/a

**Is Catalog enabled:** Yes

---

**Problem:**
The downloaded file name uses always US style date and time format, which is annoying for sorting.
Can you change to ISO 8601 combined date and time format? Timezone would be irrelevant.
See https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

**How to replicate:**
Just export any list with Chrome

**Other notes:**

**Comment by RePod** [comment]
Here's hoping casual end users don't take issue.

**Comment by windsurfer1122** [comment]
The casual user won't, but people who keep track of their purchases and archive their lists.

**Comment by windsurfer1122** [comment]
On Firefox PSDLE creates a different date/time format in the download file name.

**Comment by windsurfer1122** [comment]
Just recognized you already changed that :)

**Comment by windsurfer1122** [comment]
Works great, also handles colons for the time.

**Comment by windsurfer1122** [comment]
Side note to the commit:
The concatenated underscore should be removed and moved to the actual parameters.
To avoid the unintended trailing underscore in file names like "psdle_2019-06-19T21_52_34.289Z_.json"
Add underscore to the fallback "generic.txt" plus the single call with not only an extension.

"download" : "psdle_"+(new Date().toISOString())+(download || "_generic.txt"),
repod.psdle.exportList.download("_raw.json",JSON.stringify(raw))
