### ISSUE TITLE
Add catalog entry for en-gb

### ISSUE THREAD

**Issue by windsurfer1122** [RePod/psdle#72]
**Browser:** Firefox 68 and Chrome 75

**Method:** Extension

**Online store version and language:** Desktop en-gb

**PSDLE version:** 3.3.15

**Monkey variant:** n/a

**Is Catalog enabled:** Yes

---

**Problem:**
Missing entry for en-gb catalog.

**Other notes:**
Useful for European titles in general and UK entries in particular.

**Comment by RePod** [comment]
PSDLE doesn't pick and choose regions for Catalog. They either all have it or they don't. It uses the store's internal routing which I don't think are region specific.

Is the button on startup missing or is not functioning? Catalog results are fine for me on en-us.

To prevent most users who may not need Catalog information, it's disabled by default and must be manually enabled.

**Comment by windsurfer1122** [comment]
Maybe I misunderstood the selection on the first screen of PSDLE. I always thought that it also selects the store land for the catalog data retrieval.
As I normally want the English names of my EU games I normally choosed "en-us".
Was I mislead? So does PSDLE always use the catalog from the store land currently logged in?
Will have a close look on the weekend to avoid being a user mistake on my side.

**Comment by RePod** [comment]
Catalog is faded out to indicate it off. Maybe not super intuitive, but if a region would not have something it'd be easier to not show the button at all.

But yes it's limited to the store region and thus whatever account PSDLE reads from. There's no sense in changing it since it uses the store's code directly, which determines the region.

**Comment by windsurfer1122** [comment]
So the language is really just for the PSDLE interface.

Thanks for clarification.
