### ISSUE TITLE
Faster way to queue items and saving settings

### ISSUE THREAD

**Issue by lance8765** [RePod/psdle#74]
Hello there,

First, thank you for this awesome tool. It is the best way to check my Download List and to queue items, also now the PS3/Vita items on the Store have problems with queue because you can't put bundles, it only puts one fixed item out of all the ones in the bundle (i.e. one game, one DLC, one artbook etc.), and this is the only good alternative, as the "bad" one is to manually scroll through thousands of entries in the Download List.

Second, is it me or there was a faster way to queue items in old versions of PSDLE? Like pressing either SHIFT or CTRL and clicking on the items to make them "green", instead of clicking on each item, choose "Download to..." and wait for that button to become green? Did you remove it?

Also, will there be a way to save "settings" in PSDLE? When i export my list, i love to add other columns/properties, but every time i have to repeat the process manually.

Thank you in advance.

**Comment by RePod** [comment]
I have fixed the shift-click behavior as of 3.3.16, which should should be available on Firefox and Chrome most likely within an hour and all other versions immediately.

I've no intention of having PSDLE save data on the store, however the Export window has import and export buttons (...) of its own. When you're happy with your rows click export to generate a line you can then import on future uses.
In case you don't want to store this, in regular/CSV exports the same line can be found on the last line of the export in the second from last column.

**Comment by lance8765** [comment]
Thanks for fixing the first issue.

So there's really no way to make the other thing automatic? It's not possible to tell the program "from now on, when you click on Export View, instead of the properties "name, platform, prettySize, prettyDate", you get these and also "property, productID..." and any other property you want?
