### ISSUE TITLE
Firefox addon is blocked by Sony

### ISSUE THREAD

**Issue by azumukupoe** [RePod/psdle#75]
**Browser:** Firefox 70.0

**Method:** Extension

**Online store version and language:** Desktop ja-jp

**PSDLE version:** 3.3.16

**Monkey variant:** (Greasemonkey/Violentmonkey/etc.) (if applicable)

**Is Catalog enabled:** (No, by default/Yes)

---

**Problem:** Sony blocks access to their website when the add-on is enabled

**How to replicate:** Install the add-on version on Firefox and then access PS Store

**Other notes:**

**Comment by RePod** [comment]
Do you have a screenshot? Censor anything you feel the need to.

**Comment by azumukupoe** [comment]
> 
> 
> Do you have a screenshot? Censor anything you feel the need to.

I've already removed the add-on. Do you want me to install it again?

**Comment by RePod** [comment]
Testing Chrome 77 with no other addons other than PSDLE: no issue.

I had one issue from Firefox 70 with **NoScript** blocking various `playstation.com` sites.
Specifically, `social.playstation.com` is needed for the sign in button to appear.

I don't think PSDLE or its extension are the cause. I'm not sure what else would be considered blocked access.

**Comment by azumukupoe** [comment]
> 
> 
> Testing Chrome 77 with no other addons other than PSDLE: no issue.
> 
> I had one issue from Firefox 70 with **NoScript** blocking various `playstation.com` sites.
> Specifically, `social.playstation.com` is needed for the sign in button to appear.
> 
> I don't think PSDLE or its extension are the cause. I'm not sure what else would be considered blocked access.

I know that as I tested with Chrome before opening this and had no issues.

It must be this add-on because I was able to access the website once the add-on was disabled.

**Comment by RePod** [comment]
I'm not sure what is being blocked though. Until the extension icon is clicked, same as the Chrome version, it should have run no code on the store itself.

A screenshot (with translation if needed) would be very helpful.
