### ISSUE TITLE
New Feature to exporting tool

### ISSUE THREAD

**Issue by httan999** [RePod/psdle#79]
Browser: (Chrome 83.0.4103.106)
Method: (Extension)
Online store version and language: (Desktop) (en-us/I think it could apply to all stores)
PSDLE version: 3.3.17
Is Catalog enabled: (by default/Yes)
Problem: Adding a new feature, Property column name while exporting (type of content) such as (Game - addons - avatar - apps)

**Comment by RePod** [comment]
Sorry I forgot about this issue. I recall Github was having issues the day this was posted.

How does this feature request differ from the `category` property when exporting with Catalog enabled?

**Comment by httan999** [comment]
Thanks for your replay, and sorry I did not see the category tab, my mistake
