### ISSUE TITLE
Items Being Miscategorized

### ISSUE THREAD

**Issue by TheChrisGlass** [RePod/psdle#8]
**Browser:** Firefox 35.0.1
**Method:** Bookmarklet
**Online store version and language:** Desktop en-us
**Userscript version:** N/A
**Monkey variant:** N/A 
**Problem:** ~ Items listed under themes aren't themes
**How to replicate:** ~  
1: Initialize app
2: Filter down to PS3 and PSP
3: Filter down to just themes
4: Scroll down and note the items listed
**Other notes:** ~ 
As shown in the included image, some items under the banner of 'Theme' are decidedly not themes, like the LittleBig Planet PSP patch and unlock keys for Super Rub a Dub.
![themes](https://cloud.githubusercontent.com/assets/1724677/6048865/6092f422-ac68-11e4-8e86-1f9900d54d52.png)

**Comment by RePod** [comment]
This is a known issue. I plan on rewriting the shown categories to be scalable and only based on categories that are present in the list, which would alleviate this as well as include outliers such as "Unlocks".

Expect it soon™.

**Comment by RePod** [comment]
Whoops.

**Comment by RePod** [comment]
Going to assume this is fixed. If not, feel free to re-open.
