### ISSUE TITLE
I was able to use PSDLE using a link provided by DelistedGames.com

### ISSUE THREAD

**Issue by enoky** [RePod/psdle#86]
To my surprise, this actually worked!!! I was able to use PSDLE today (Nov, 3rd, 2020) using a link posted on the following site.

https://delistedgames.com/get-the-old-playstation-store-back-for-now

Hopefully SONY doesn't kill this link anytime soon!

**Comment by XploitOcelot** [comment]
Still working! I'm just up to backup everything I purchased. Thanks!
