### ISSUE TITLE
Valkyrie / Old store

### ISSUE THREAD

**Issue by KuromeSan** [RePod/psdle#90]
its still 'possible' to access the old store using some hacks

https://addons.mozilla.org/en-GB/firefox/addon/valkyrie-ps-store/
https://github.com/KuromeSan/ValkyrieStore
basically- everything still works providing u replace the redirect response with the html code for the store from your region-

**Comment by RePod** [comment]
I would recommend for security/privacy, if viable, not bundling a snapshot of sorts of the store and instead relying on Wayback. The window of time for the store to reflect the proper region/language seems worth the small inconvenience.

Also while I do not endorse the extension I'll continue to provide support for Valkyrie (#91).

**Comment by KuromeSan** [comment]
i just dont get why thats better though? if anything downloading from some server seems like the less secure option because then web.archive.org could put whatever they want in into it without anyone knowing ?

**Comment by KuromeSan** [comment]
anyway
https://github.com/KuromeSan/ValkyrieStore/blob/66976cad853cb990b47a8a73d8910c3fbdfc9ce0/background.js#L21 i added an option to do what you asked to the new 'options' menu thing i made :d

**Comment by lance8765** [comment]
It's good to see the old site back! And thanks for updating PSDLE.

However, i don't know if it's caused by a bug or by the old site itself, but it no longer shows sizes (both "Size" and "prettySize") for PS4/PS5/PSVR content with Catalog enabled, they're all "N/A" or blank for me. Shortly before the closure, the generated list lacked "Description", too, but these work again as of now.

**Comment by RePod** [comment]
Backported PSDLE Gotham's Catalog cache which should benefit everyone.
File sizes (at least `prettySize`) should be improved when using Catalog.

**Comment by lance8765** [comment]
Yeah now it reports more sizes, thanks. Not all of them though, but it's better than nothing.

**Comment by lance8765** [comment]
It's gone for good.

**Comment by RePod** [comment]
The storefront that was killed 3 times.
