### ISSUE TITLE
vTesting Infinity (Valkyrie) blocks account menu content

### ISSUE THREAD

**Issue by slammajamma28** [RePod/psdle#97]
**Browser:** Firefox 97.0.1 (64-bit)

**Method:** Extension

**Online store version and language:** Desktop en-us

**PSDLE version:** 4.0.7

**Is Catalog enabled:** No

---

**Problem:** When I click into one of the user account menus, a "vTesting Infinity (Valkyrie)" overlay blocks some of the content.

**How to replicate:** In the account menu, click on Payment Management, Redeem Code, or Subscription Management

**Other notes:** See photo below for an example of the Subscription Management screen with PSDLE on and off.

![PSDLE-bug](https://user-images.githubusercontent.com/1652496/156240540-d2ba77e0-33fe-4ae9-b6e6-4b22ff675927.png)

**Comment by RePod** [comment]
I'll get back to you as soon as any of them feel like loading for me.
As of now, they all fittingly use `transact.playstation.com` via iframe so PSDLE Valkyrie will need to be a little more particular in which iframe it wants. Although, if they all load the same Ember application it might not matter but I could switch the extension back to the old "click here to start" button.

**Comment by sakapoodle** [comment]
@slammajamma28 what you can do in the meanwhile is use something like Adblock Plus or uBlock Origin and block the element.
Once the issue has been resolved in a future deployment of PSDLE you can remove the filtering rule.
You can block (temporarily remove) the PSDLE Valkyrie element by right-clicking on it and select "block with..." or in uBlock Origin do this:

- Go to the extension settings > My filters: chrome-extension://cjpalhdlnbpafiamejdnhcphjbkeiagm/dashboard.html#1p-filters.html
- Add this line at the bottom of the input textarea: `transact.playstation.com###sub_container`
